enum LoggerLabels {
  MAIN = 'MAIN',

  STREAM_READER = 'STREAM_READER',
  WIKI_CLIENT = 'WIKI_CLIENT',

  CSV_PROCESSOR = 'CSV_PROCESSOR',

  PROCESSOR_STATE_HEADERS = 'PROCESSOR_STATE_HEADERS',
  PROCESSOR_STATE_RECORDS = 'PROCESSOR_STATE_RECORDS',
}

export { LoggerLabels };
