enum LoggerLabels {
  MAIN = 'MAIN',
  PROCESSOR = 'PROCESSOR',
  PROCESSOR_STATE_HEADERS = 'PROCESSOR_STATE_HEADERS',
  PROCESSOR_STATE_RECORDS = 'PROCESSOR_STATE_RECORDS',
}

export { LoggerLabels };
