enum LoggerLabels {
  MAIN = 'MAIN',

  WIKI_CLIENT = 'WIKI_CLIENT',

  PROCESSOR = 'PROCESSOR',

  PROCESSOR_STATE_HEADERS = 'PROCESSOR_STATE_HEADERS',
  PROCESSOR_STATE_RECORDS = 'PROCESSOR_STATE_RECORDS',
}

export { LoggerLabels };
